apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpbook
  labels:
    app: phpbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpbook
  template:
    metadata:
      labels:
        app: phpbook
    spec:
      containers:
      - name: phpbook
        image: dvasanth26/phpstatic:latest
        ports:
        - containerPort: 80
